apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-student78.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.variables }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
