apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  appsettings: |
    {
      "ConnectionStrings": {
        "PgConnection": "server={{ .Values.config.dbhost }}; port={{ .Values.config.dbport }}; database={{ .Values.config.dbname }}; user id={{ .Values.config.dbuser }}; password={{ .Values.config.dbpass }};"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*"
    }
